apiVersion: v1
kind: ConfigMap
metadata:
  name: member-config
  namespace: dg0410-lifesub-ns
data:
  POSTGRES_HOST: "postgres-member-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "member"
  JWT_ACCESS_TOKEN_VALIDITY: "3600000"
  JWT_REFRESH_TOKEN_VALIDITY: "86400000"
