apiVersion: v1
kind: ConfigMap
metadata:
  name: mysub-config
  namespace: dg0410-lifesub-ns
data:
  POSTGRES_HOST: "postgres-mysub-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "mysub"
  FEE_LEVEL_COLLECTOR: "50000"
  FEE_LEVEL_ADDICT: "100000"
