apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: dg0410-lifesub-ns
  labels:
    app: member
spec:
  selector:
    app: member
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
